name: Certify build on push, pull-requests

on: 
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Execute Permissions
      run: chmod +x gradlew
    - name: Build and run tests
      run: ./gradlew build
